<a href="https://colab.research.google.com/github/ashu5644/Machine-Learning-Tools/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Python VS C Language**
1. Python language is human friendly and easier to code compared to C language.
2. Python is relatively slow compared to C language.
3. Python is application centric while C is OS centric i.e C is preferred in applications where we need to work close to OS and python is preffered in applications where we need to work close to software logic and don't care much on OS memory mangement etc.

Numpy is written in C with python wrapper, so it gives us comfort of python syntax with speed of C.
Complex mathematical operations can be computed very fast and efficently in Numpy, which are difficult to do with core python data structuers.


**Properties of Numpy**
 1. Numpy core object is N-Dimnesional array
 2. N-D array objects are homogeneous always, i.e single type of data can be stored in an object, which is similar to C language objects and essential for speed.
 3. N-D array objects are of fixed size, i.e object size is static and not dynamic i.e predefined size, which is similar to C language objects and essential for speed.



Standalone Functions (np.func)
  - They are designed to work on any array-like input (e.g., lists, tuples, numpy arrays) and often provide a more general or high-level operation.

Array Methods (np_array.func)
  - These methods are specific to numpy array instances and often provide operations or transformations that are tightly coupled with the array's internal structure.


**N-D Array Creation**

Difference between np.arange, np.linspace is following:
 - in np.arange we specify step size of gap b/w consecutive data points, while in np.linspace we specify num_samples to generate as third parameter

In [ ]:
import numpy as np

In [70]:
# Method-1
arr_1d = np.array([[1,2,3,4]], dtype=np.int32)
arr_2d = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int32)
print(arr_1d)
print("*"*50)
print(arr_2d)
print("*"*50)
# Method-2
arr_zeros_nd = np.zeros((3,5))
arr_ones_nd = np.ones((3,5))
arr_identity_nd = np.identity(5) # only square arrays are allowed
print(arr_zeros_nd)
print("*"*50)
print(arr_ones_nd)
print("*"*50)
print(arr_identity_nd)
print("*"*50)
# Method-3
arr_2 = np.arange(start=0,stop=5,step=1)
print(arr_2)
print("*"*50)
# Method-4
arr_3 = np.linspace(start=0,stop=5,num=2)
print(arr_3)
# Method-5
arr_4 = np.random.randint(0,10,(5,4)) # start, stop, shape
print("*"*50)
print(arr_4)
arr_5 = np.random.rand(5,4) # shape only, default range b/w (0,1)
print("*"*50)
print(arr_5)
arr6 = np.random.uniform(0,100,(3,4))
print("*"*50)
print(arr6)
# Single-Number
print("*"*50)
print(np.random.randint(0,10),np.random.random(),np.random.uniform(0,100))

[[1 2 3 4]]
**************************************************
[[1 2 3 4]
 [5 6 7 8]]
**************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
**************************************************
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
**************************************************
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
**************************************************
[0 1 2 3 4]
**************************************************
[0. 5.]
**************************************************
[[4 2 5 1]
 [2 5 4 3]
 [8 5 2 4]
 [2 6 1 4]
 [4 5 8 8]]
**************************************************
[[0.18070332 0.78990806 0.50230626 0.3425524 ]
 [0.10720678 0.47250057 0.27482038 0.01690418]
 [0.41666598 0.81187426 0.95235491 0.45389741]
 [0.75138305 0.04646275 0.84861465 0.9950047 ]
 [0.67094108 0.79604752 0.95699795 0.27639219]]
********************************************

**Properties and attributes of N-D array**

Differecne between shape and size is following:
 - size represents total number of items, while shape represents number of items in each dimension.
 - astype function can be crucial in data cleaning steps to decrease memory footprint of data as pper requirements

In [ ]:
arr_4 = np.array([[2,3,4],[5,6,7]])
print(f"shape: {arr_4.shape}")
print("*"*50)
print(f"size: {arr_4.size}")
print("*"*50)
print(f"ndim: {arr_4.ndim}")
print("*"*50)
print(f"dtype: {arr_4.dtype}")

print("*"*50)
print(arr_4.astype('float').dtype)

shape: (2, 3)
**************************************************
size: 6
**************************************************
ndim: 2
**************************************************
dtype: int64
**************************************************
float64


**Python List VS Numpy N-D Arrays**
1. N-D arrays are ***faster***
  1. Due to broadcasting support, no loop requirement, multiple operations being done in parallel in numpy unlike sequential operations in python
2. N-D arrays are ***convinent***
  1. Syntax of n-d array operations is more human friendly and minimal compared to raw python
3. N-D arrays occupy ***less memory*** for same data
  1.  python array stores reference and values of all data-points, as stored location can be non-contguous due to non-predefined/dynamic/hetrogeneous data-type of python lists.
  2. numpy array stores data points in continuous memory block due to predefined and homogenous data-type, that's why it's more memory efficient

In [51]:
# Less Memory
import numpy as np
neles = 10**5
arr_numpy = np.arange(neles)
arr_python = list(range(neles))

import sys
python_list_size = sys.getsizeof(arr_python) + sum(sys.getsizeof(item) for item in arr_python)
numpy_list_size = arr_numpy.nbytes
print(f"python_list_size(Bytes): {python_list_size}")
print(f"numpy_list_size(Bytes): {numpy_list_size}")
print(f"Memory-Ratio: {numpy_list_size/python_list_size}") # 22% of python size only

python_list_size(Bytes): 3600052
numpy_list_size(Bytes): 800000
Memory-Ratio: 0.22221901239204322


In [52]:
# Less Time
import time
arr_numpy1 = np.arange(neles)
arr_numpy2 = np.arange(neles)
t1 = time.time()
arr_numpy3 = arr_numpy1+arr_numpy2
t_numpy = time.time()-t1
print(f"Time-Numpy: {t_numpy} seconds")
arr_py1 = range(neles)
arr_py2 = range(neles)
t1 = time.time()
arr_py3 = sum(arr_py1)+sum(arr_py2)
t_python = time.time()-t1
print(f"Time-Python: {t_python} seconds")
print(f"Ratio: {t_numpy/t_python}") # 5% of python time

Time-Numpy: 0.0005340576171875 seconds
Time-Python: 0.007066965103149414 seconds
Ratio: 0.07557099962889241


**Reshaping Numpy Array**

1. Ravel Return only reference/view of the original array
2. Flatten Return copy of the original array

In [ ]:
import numpy as np
arr = np.random.randint(0,20,(5,4))
print(arr)
# Reshape
print("*"*50)
print(arr.reshape((4,5)))
# Ravel (Make 1d array)
print("*"*50)
print(arr.ravel()) # Return only reference/view of the original array
# Flatten (Make 1d array)
print("*"*50)
print(arr.flatten()) # Return copy of the original array
# Transpose
print("*"*50)
print(np.transpose(arr, (1,0)))
# Stacking (vertical, horizontal)
arr1 = np.random.randint(0,10,(3,2))
arr2 = np.random.randint(0,10,(3,2))
print("*"*50)
print(np.vstack((arr1,arr2))) # top-down
print("*"*50)
print(np.hstack((arr1,arr2))) # left-right
# Breaking/Splitting (vertical, horizontal)
print("*"*50)
print(np.vsplit(np.vstack((arr1,arr2)),2)) # only equal shape divison allowed
print("*"*50)
print(np.hsplit(np.hstack((arr1,arr2)),2)) # only equal shape divison allowed

[[18  8  9  4]
 [10 15  3  1]
 [ 0 17  8 14]
 [18  5  0 11]
 [13 14 18  1]]
**************************************************
[[18  8  9  4 10]
 [15  3  1  0 17]
 [ 8 14 18  5  0]
 [11 13 14 18  1]]
**************************************************
[18  8  9  4 10 15  3  1  0 17  8 14 18  5  0 11 13 14 18  1]
**************************************************
[18  8  9  4 10 15  3  1  0 17  8 14 18  5  0 11 13 14 18  1]
**************************************************
[[18 10  0 18 13]
 [ 8 15 17  5 14]
 [ 9  3  8  0 18]
 [ 4  1 14 11  1]]
**************************************************
[[5 1]
 [9 5]
 [8 3]
 [0 7]
 [2 9]
 [3 6]]
**************************************************
[[5 1 0 7]
 [9 5 2 9]
 [8 3 3 6]]
**************************************************
[array([[5, 1],
       [9, 5],
       [8, 3]]), array([[0, 7],
       [2, 9],
       [3, 6]])]
**************************************************
[array([[5, 1],
       [9, 5],
       [8, 3]]), array([[0, 7],
       [2, 

**Indexing, Slicing, Iteration of N-D arrays**

In [54]:
# Indexing and slicing
arr6 = np.arange(24).reshape(4,6)
print(arr6)
print("*"*50)
print(arr6[2]) # extract 2nd row
print("*"*50)
print(arr6[:, 2]) # extract 2nd column
print("*"*50)
print(arr6[3, 2]) # extract 3row, 2nd column
print("*"*50)
print(arr6[0:3, 0:2]) # extract first 3 rows, first 2 columns
print("*"*50)
print(arr6[[0,2], [1,3]]) # extract individual elements by (x,y) cordinates specify as separate list
# Indexing with boolean-array
print("*"*50)
print(arr6[arr6>15]) # always gives 1-d array, as this opration works on elementwise data, and output can be of any irregaulr shape so final output comes as 1-d always.
# Iteration
print("*"*50)
for i in np.nditer(arr6):
    print(i)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
**************************************************
[12 13 14 15 16 17]
**************************************************
[ 2  8 14 20]
**************************************************
20
**************************************************
[[ 0  1]
 [ 6  7]
 [12 13]]
**************************************************
[ 1 15]
**************************************************
[16 17 18 19 20 21 22 23]
**************************************************
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


**Fancy Indexing**

In [55]:
# extract 1st3rd row, 0th 2nd column (it is bit tricky)
# can't specify both row and column selection in sngle operation, it will result into specific element selection as shown above
arr1 = arr6[:,[0,2]][[1,3],:] # 0th 2nd column followed by 1stand 3row
arr2 = arr6[[1,3],:][:,[0,2]] # 1stand 3row followed by 0th 2nd column
print("*"*50)
print(arr1)
print("*"*100)
print(arr2)

**************************************************
[[ 6  8]
 [18 20]]
****************************************************************************************************
[[ 6  8]
 [18 20]]


**Numpy Operations**

In [75]:
# Multiply by scalr
print(arr6)
arr7 = arr6*2
print("*"*50)
print(arr7)
# Boolean operation
print("*"*50)
print(arr7<10)
# Dot product
arr8 = np.random.randint(0,10,(3,4))
arr9 = np.random.randint(0,10,(4,5))
print("*"*50)
print(np.dot(arr8,arr9), np.dot(arr8,arr9).shape)
# Min, Max, median, mode, mean, std. etc. etc along different axes (aggregate oprations)
print("*"*50)
print(np.min(arr8), np.min(arr8,axis=0),np.min(arr8,axis=1))
# percentile
print(np.percentile(arr8,25), np.percentile(arr8,25,axis=0), np.percentile(arr8,25,axis=1))
# sort
print(np.sort(arr8), np.sort(arr8, axis=0), np.sort(arr8,axis=1))
# argmin, argmax
print("*"*50)
print(np.argmin(arr8), np.argmin(arr8,axis=0),np.argmin(arr8,axis=1))
# Pointwise operations
print("*"*50)
print(np.exp(arr8))
print("*"*50)
print(np.sin(arr8))

[[40.19075111 81.24674428 61.25281694 96.49636336]
 [56.26495984 96.70568645 39.29883989  2.03230255]
 [ 7.24738638 93.99112315 89.23412868 51.2499003 ]]
**************************************************
[[ 80.38150221 162.49348856 122.50563387 192.99272673]
 [112.52991969 193.41137291  78.59767978   4.0646051 ]
 [ 14.49477277 187.98224629 178.46825736 102.49980061]]
**************************************************
[[False False False False]
 [False False False  True]
 [False False False False]]
**************************************************
[[ 48  12  63  22  43]
 [ 64   0 144  75  58]
 [ 60  57  84  82  82]] (3, 5)
**************************************************
0 [0 0 3 0] [0 0 1]
0.0 [1.5 0.  3.  0.5] [0.  0.  2.5]
[[0 0 3 4]
 [0 0 8 9]
 [1 3 3 6]] [[0 0 3 0]
 [3 0 3 1]
 [9 6 8 4]] [[0 0 3 4]
 [0 0 8 9]
 [1 3 3 6]]
**************************************************
0 [0 0 0 1] [0 1 3]
**************************************************
[[1.00000000e+00 1.00000000e+00 2.008

**Broadcasting N-D arrays**

 - The trem broadcasting referes to ability of numpy arrays to treat arrays of different shapes during elementwise arthemetic operations. these operations are done on corrosponding elements of arrays. if two arrays are of exact same size, these operations are smoothly performed.
 - If dimensions of two arrays don't match, numpy make it still possible to do elemetwise operations by broadcasting smaller size array to large size array by broadcasting smaller array by repeating its elements.
 - Either array dimension is 1, otherwise dimnesional should have same number of elements in both arrays.
    - ex: (1,1) (a,b) allowed
    - ex: (1,b) (a,b) allowed
    - ex: (a,1) (a,b) allowed
    - ex: (a,c) (a,b) not allowed
    - ex: (a,1) (c,b) not allowed
    - ex: scalar (c,b) allowed

In [62]:
arr1 = np.random.randint(0,10,(1,3))
arr2 = np.random.randint(0,10,(6,3))
print(arr1)
print("*"*50)
print(arr2)
print("*"*50)
print(arr1+arr2)

[[8 8 4]]
**************************************************
[[4 0 6]
 [7 5 0]
 [5 3 6]
 [7 2 7]
 [1 4 2]
 [6 9 1]]
**************************************************
[[12  8 10]
 [15 13  4]
 [13 11 10]
 [15 10 11]
 [ 9 12  6]
 [14 17  5]]
